export const BACKEND_BASE_URL = process.env.REACT_APP_BACKEND_URL;
export const ABOUT_SAVED_AMOUNT = process.env.REACT_APP_ABOUT_SAVED_AMOUNT;
export const ABOUT_SOLD_PRODUCTS = process.env.REACT_APP_ABOUT_SOLD_PRODUCTS;
export const ABOUT_SATISFIED_CLIENTS = process.env.REACT_APP_ABOUT_SATISFIED_CLIENTS;
export const ABOUT_DELIVERED_PACKAGES = process.env.REACT_APP_ABOUT_DELIVERED_PACKAGES;