# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - gymfitbulgaria(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@main


    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: npm install, build, and test
      env:
        CI: false

      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory:  .

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: gymfitbulgaria
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E6986FC1078B4F44964B8B3BAD7892FB }}
        package: ./build

